### ISSUE TITLE
Problemas com o Gulp

### ISSUE THREAD

**Issue by ribeiroevandro** [willianjusten/will-jekyll-template#1]
Abaixo o erro gerado após executar o comando `gulp`

```
evandro in ~/projects/personal λ gulp
[15:05:50] Using gulpfile ~/projects/personal/gulpfile.js
[15:05:50] Starting 'js'...
[15:05:50] Starting 'stylus'...
[15:05:50] Finished 'stylus' after 3.64 ms
[15:05:50] Starting 'jekyll-build'...
[15:05:50] Starting 'watch'...
[15:05:50] 'watch' errored after 9.21 ms
[15:05:50] Error: watch ENOSPC
    at errnoException (fs.js:1030:11)
    at FSWatcher.start (fs.js:1062:11)
    at Object.fs.watch (fs.js:1087:11)
    at Gaze._watchDir (/home/evandro/projects/personal/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:289:30)
    at /home/evandro/projects/personal/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/home/evandro/projects/personal/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at Object.forEachSeries (/home/evandro/projects/personal/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:66:3)
    at Gaze._initWatched (/home/evandro/projects/personal/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:354:10)
    at Gaze.add (/home/evandro/projects/personal/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:177:8)
    at new Gaze (/home/evandro/projects/personal/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:74:10)
Configuration file: /home/evandro/projects/personal/_config.yml
            Source: /home/evandro/projects/personal
       Destination: /home/evandro/projects/personal/_site
      Generating... 
                    done.
 Auto-regeneration: disabled. Use --watch to enable.
[15:05:52] Finished 'jekyll-build' after 1.21 s
[15:05:52] Finished 'js' after 1.22 s
evandro in ~/projects/personal λ
```

**Comment by willianjusten** [comment]
Estranho @ribeiroevandro , eu tentei gerar o erro e não consegui. Mas aparentemente vi que é um erro no Linux, em que você precisa setar um número maior de arquivos para ficarem no "watch".

Tenta rodar esse comando:

`echo fs.inotify.max_user_watches=582222 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

**Comment by ribeiroevandro** [comment]
@willianjusten obrigado pela ajuda, em casa não tive o problema, vou testar amanhã do trabalho onde apresentou esse erro.

**Comment by willianjusten** [comment]
Opa, que bom que funcionou. Pelo erro, eu realmente acho que seja aquilo ali de aumentar o número de arquivos no watch, aí é só mudar e pronto =)
