### ISSUE TITLE
Error: spawn jekyll ENOENT

### ISSUE THREAD

**Issue by noxidsoft** [willianjusten/will-jekyll-template#45]
I am on Windows 10, I tried the spawn('jekyll.bat', ['build']) where it is indicated it should go, but no go.

C:\xampp\htdocs\dev\8.0.0>npm install
cardsjekyll@1.0.0 C:\xampp\htdocs\dev_noxidsoft_flat\8.0.0
+-- graceful-fs@4.1.4
`-- minimatch@3.0.2

npm WARN cardsjekyll@1.0.0 No repository field.

C:\xampp\htdocs\dev\8.0.0>gulp
[17:55:40] Using gulpfile C:\xampp\htdocs\dev\8.0.0\gulpfile.js
[17:55:40] Starting 'js'...
[17:55:40] Starting 'stylus'...
[17:55:40] Finished 'stylus' after 4.51 ms
[17:55:40] Starting 'jekyll-build'...
[17:55:40] Starting 'watch'...
[17:55:41] Finished 'watch' after 1.1 s
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn jekyll ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:139:18)
    at node.js:999:3

**Comment by noxidsoft** [comment]
Jeet issue, update to appropriate version.
